import { and, desc, eq, gte, inArray } from 'drizzle-orm';
import { getDb } from '@/db/client';
import { applications, jobs, users } from '@/db/schema';
import { logger } from '@/lib/logger';
import { sendHiredNearbyPush } from '@/lib/push';

const RADIUS_METERS = 10_000;
const FANOUT_MAX = 50;
interface HiredNearbyEntry { applicationId: string; hiredFirstName: string; jobTitle: string; area: string | null; city: string | null; hiredAt: string; }
function distanceMeters(a: [number, number], b: [number, number]): number { const [lng1, lat1] = a, [lng2, lat2] = b; const dLat = (lat2 - lat1) * Math.PI / 180, dLng = (lng2 - lng1) * Math.PI / 180; const x = Math.sin(dLat / 2) ** 2 + Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLng / 2) ** 2; return 6_371_000 * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x)); }
function coords(location: typeof users.$inferSelect['location']): [number, number] | null { const value = location?.coordinates; return Array.isArray(value) && value.length === 2 && typeof value[0] === 'number' && typeof value[1] === 'number' ? [value[0], value[1]] : null; }
export async function fanOutOnHire(input: { applicationId: string; excludeUserIds?: string[] }): Promise<{ pushed: number }> { const [app] = await getDb().select().from(applications).where(eq(applications.id, input.applicationId)).limit(1); if (!app) return { pushed: 0 }; const [job] = await getDb().select().from(jobs).where(eq(jobs.id, app.jobId)).limit(1); if (!job?.geo) return { pushed: 0 }; const [seeker] = await getDb().select({ name: users.name }).from(users).where(eq(users.id, app.seekerId)).limit(1); const all = await getDb().select({ id: users.id, location: users.location, notificationPrefs: users.notificationPrefs }).from(users).where(and(eq(users.role, 'seeker'), eq(users.isVerified, true), eq(users.isActive, true))).limit(500); const exclude = new Set([app.seekerId, ...(input.excludeUserIds ?? [])]); let pushed = 0; for (const candidate of all) { if (pushed >= FANOUT_MAX) break; const point = coords(candidate.location); if (!point || exclude.has(candidate.id) || candidate.notificationPrefs.jobs === false || distanceMeters([job.geo.x, job.geo.y], point) > RADIUS_METERS) continue; void sendHiredNearbyPush({ recipientId: candidate.id, hiredFirstName: (seeker?.name ?? 'A worker').split(' ')[0] ?? 'A worker', jobTitle: job.title, area: job.area ?? null }).catch((err) => logger.warn({ err, recipientId: candidate.id }, 'hired-nearby push failed')); pushed += 1; } return { pushed }; }
export async function listNearbyHires(input: { callerId: string; limit?: number; radiusMeters?: number }): Promise<HiredNearbyEntry[]> { const limit = Math.max(1, Math.min(20, input.limit ?? 5)); const [caller] = await getDb().select({ location: users.location }).from(users).where(eq(users.id, input.callerId)).limit(1); const callerCoords = coords(caller?.location ?? null); if (!callerCoords) return []; const since = new Date(Date.now() - 86_400_000); const rows = await getDb().select({ app: applications, job: jobs }).from(applications).innerJoin(jobs, eq(applications.jobId, jobs.id)).where(and(eq(applications.status, 'hired'), gte(applications.hiredAt, since))).orderBy(desc(applications.hiredAt)).limit(limit * 10); const nearby = rows.filter(({ job }) => job.geo && distanceMeters(callerCoords, [job.geo.x, job.geo.y]) <= (input.radiusMeters ?? RADIUS_METERS)); const seekerIds = [...new Set(nearby.map(({ app }) => app.seekerId))]; const seekers = seekerIds.length ? await getDb().select({ id: users.id, name: users.name }).from(users).where(inArray(users.id, seekerIds)) : []; const names = new Map(seekers.map((s) => [s.id, s.name])); return nearby.filter(({ app }) => app.seekerId !== input.callerId).slice(0, limit).map(({ app, job }) => ({ applicationId: app.id, hiredFirstName: (names.get(app.seekerId) ?? 'A worker').split(' ')[0] ?? 'A worker', jobTitle: job.title, area: job.area ?? null, city: job.city ?? null, hiredAt: app.hiredAt!.toISOString() })); }
