import { and, desc, eq, inArray, ne, sql } from 'drizzle-orm';
import { getDb } from '@/db/client';
import { users, walletTransactions } from '@/db/schema';
import { errors } from '@/lib/errors';
import { env } from '@/config/env';
import { requestPayout } from '@/lib/paymentAggregator';
import type { PublicWalletTransaction, WalletKind, WalletStatus } from './walletTransaction.model';

export interface EarningsSummary { totalEarnedPaise: number; pendingPaise: number; hireCount: number; cashLogCount: number; cashLogPaise: number; quickWorkCount: number; quickWorkPaise: number; currency: 'INR'; }
function publicRow(row: typeof walletTransactions.$inferSelect): PublicWalletTransaction { return { id: row.id, amount: row.amount, currency: row.currency, kind: row.kind as WalletKind, status: row.status as WalletStatus, description: row.description, jobId: row.jobId ?? null, applicationId: row.applicationId ?? null, settledAt: row.settledAt?.toISOString() ?? null, grossPaise: row.grossPaise ?? null, feePaise: row.feePaise ?? null, createdAt: row.createdAt.toISOString() }; }
async function insertTransaction(values: typeof walletTransactions.$inferInsert): Promise<typeof walletTransactions.$inferSelect | null> { const [row] = await getDb().insert(walletTransactions).values(values).onConflictDoNothing().returning(); return row ?? null; }
export async function creditOnHire(input: { userId: string; applicationId: string; jobId: string; amount: number; jobTitle?: string }): Promise<boolean> { return Boolean(await insertTransaction({ userId: input.userId, applicationId: input.applicationId, jobId: input.jobId, amount: Math.max(0, input.amount), currency: 'INR', kind: 'hire_payment', status: 'settled', description: input.jobTitle ? `Hired for "${input.jobTitle}"` : 'Hired for a job', settledAt: new Date() })); }
export async function recordCashLog(input: { userId: string; amount: number; description: string; workedOn?: string }): Promise<PublicWalletTransaction> { const [row] = await getDb().insert(walletTransactions).values({ userId: input.userId, amount: Math.max(0, input.amount), currency: 'INR', kind: 'cash_log', status: 'settled', description: input.description.trim().slice(0, 240), settledAt: input.workedOn ? new Date(input.workedOn) : new Date() }).returning(); return publicRow(row!); }
export async function deleteCashLog(userId: string, transactionId: string): Promise<boolean> { const rows = await getDb().delete(walletTransactions).where(and(eq(walletTransactions.id, transactionId), eq(walletTransactions.userId, userId), eq(walletTransactions.kind, 'cash_log'))).returning({ id: walletTransactions.id }); return rows.length > 0; }
export function splitCommission(grossPaise: number): { feePaise: number; netPaise: number } { const gross = Math.max(0, Math.round(grossPaise)); const feePaise = Math.round((gross * env.DOONDO_COMMISSION_BPS) / 10_000); return { feePaise, netPaise: gross - feePaise }; }
export async function creditQrCollection(input: { userId: string; grossPaise: number; description: string }): Promise<PublicWalletTransaction> { const { feePaise, netPaise } = splitCommission(input.grossPaise); const [row] = await getDb().insert(walletTransactions).values({ userId: input.userId, amount: netPaise, currency: 'INR', kind: 'qr_collection', status: 'settled', description: input.description.trim().slice(0, 240), settledAt: new Date(), grossPaise: Math.round(input.grossPaise), feePaise }).returning(); return publicRow(row!); }
export async function getWithdrawableBalance(userId: string): Promise<number> { const [row] = await getDb().select({ total: sql<number>`coalesce(sum(${walletTransactions.amount}), 0)::int` }).from(walletTransactions).where(and(eq(walletTransactions.userId, userId), inArray(walletTransactions.kind, ['qr_collection', 'payout']), ne(walletTransactions.status, 'reversed'))); return row?.total ?? 0; }
export async function requestWithdrawal(input: { userId: string; amountPaise: number }): Promise<PublicWalletTransaction> { const amount = Math.round(input.amountPaise); if (amount <= 0) throw errors.validation(null, 'Enter an amount to withdraw.'); const [user] = await getDb().select({ payoutBank: users.payoutBank }).from(users).where(eq(users.id, input.userId)).limit(1); const bank = user?.payoutBank; if (!bank) throw errors.validation(null, 'Add a bank account before withdrawing.'); if (!bank.verified) throw errors.validation(null, 'Your bank account is not verified yet.'); if (amount > await getWithdrawableBalance(input.userId)) throw errors.validation(null, 'Amount exceeds your withdrawable balance.'); const [created] = await getDb().insert(walletTransactions).values({ userId: input.userId, amount: -amount, currency: 'INR', kind: 'payout', status: 'pending', description: 'Withdrawal to bank account' }).returning(); let row = created!; try { const result = await requestPayout({ userId: input.userId, amountPaise: amount, accountNumber: bank.accountNumber, ifsc: bank.ifsc }); row = (await getDb().update(walletTransactions).set({ status: result.status === 'failed' ? 'reversed' : 'settled', settledAt: result.status === 'failed' ? null : new Date() }).where(eq(walletTransactions.id, row.id)).returning())[0]!; } catch { row = (await getDb().update(walletTransactions).set({ status: 'reversed' }).where(eq(walletTransactions.id, row.id)).returning())[0]!; throw errors.validation(null, 'Withdrawal could not be processed. Try again.'); } return publicRow(row!); }
export async function listForUser(userId: string, limit = 50): Promise<PublicWalletTransaction[]> { const rows = await getDb().select().from(walletTransactions).where(eq(walletTransactions.userId, userId)).orderBy(desc(walletTransactions.createdAt)).limit(limit); return rows.map(publicRow); }
// `quick_work_payment` included alongside hire_payment/cash_log — found
// missing live while verifying Quick Work end-to-end (seeker-plan.md
// §19's "no separate Quick Work wallet — it appears in this exact
// existing summary" requirement was only half true: the transaction
// list already included it, but this hard-coded kind allowlist silently
// left it out of every headline total).
export async function summarize(userId: string): Promise<EarningsSummary> { const rows = await getDb().select({ kind: walletTransactions.kind, status: walletTransactions.status, sum: sql<number>`coalesce(sum(${walletTransactions.amount}), 0)::int`, count: sql<number>`count(*)::int` }).from(walletTransactions).where(and(eq(walletTransactions.userId, userId), inArray(walletTransactions.kind, ['hire_payment', 'cash_log', 'quick_work_payment']))).groupBy(walletTransactions.kind, walletTransactions.status); let totalEarnedPaise = 0, pendingPaise = 0, hireCount = 0, cashLogCount = 0, cashLogPaise = 0, quickWorkCount = 0, quickWorkPaise = 0; for (const row of rows) { if (row.status === 'settled') totalEarnedPaise += row.sum; else if (row.status === 'pending') pendingPaise += row.sum; if (row.kind === 'hire_payment') hireCount += row.count; if (row.kind === 'cash_log') { cashLogCount += row.count; cashLogPaise += row.sum; } if (row.kind === 'quick_work_payment') { quickWorkCount += row.count; quickWorkPaise += row.sum; } } return { totalEarnedPaise, pendingPaise, hireCount, cashLogCount, cashLogPaise, quickWorkCount, quickWorkPaise, currency: 'INR' }; }
