import { and, desc, eq, inArray, sql } from 'drizzle-orm';
import { getDb } from '@/db/client';
import { referrals, users, walletTransactions } from '@/db/schema';
import { logger } from '@/lib/logger';
import { sendReferralBonusPush } from '@/lib/push';
import type { PublicReferral, ReferralStatus } from './referral.model';

export const REFERRAL_BONUS_PAISE = 10_000;
function publicRow(row: typeof referrals.$inferSelect): PublicReferral { return { id: row.id, referrerId: row.referrerId, refereeId: row.refereeId, jobId: row.jobId, applicationId: row.applicationId ?? null, status: row.status as ReferralStatus, bonusPaise: row.bonusPaise ?? null, hiredAt: row.hiredAt?.toISOString() ?? null, createdAt: row.createdAt.toISOString() }; }
export async function recordReferral(input: { referrerId: string; refereeId: string; jobId: string; applicationId: string }): Promise<boolean> { if (input.referrerId === input.refereeId) return false; const [row] = await getDb().insert(referrals).values({ ...input, status: 'pending' }).onConflictDoNothing().returning({ id: referrals.id }); return Boolean(row); }
export async function creditOnFirstShift(input: { refereeId: string; jobId: string; applicationId: string }): Promise<void> { const [referral] = await getDb().select().from(referrals).where(and(eq(referrals.refereeId, input.refereeId), eq(referrals.jobId, input.jobId), eq(referrals.status, 'pending'))).limit(1); if (!referral) return; try { await getDb().transaction(async (tx) => { await tx.insert(walletTransactions).values([{ userId: referral.referrerId, amount: REFERRAL_BONUS_PAISE, currency: 'INR', kind: 'adjustment', status: 'settled', description: 'Referral bonus — your friend started their first shift', applicationId: input.applicationId, settledAt: new Date() }, { userId: referral.refereeId, amount: REFERRAL_BONUS_PAISE, currency: 'INR', kind: 'adjustment', status: 'settled', description: 'Welcome bonus — for starting your first shift on Doondo', applicationId: input.applicationId, settledAt: new Date() }]).onConflictDoNothing(); await tx.update(referrals).set({ status: 'hired', bonusPaise: REFERRAL_BONUS_PAISE, hiredAt: new Date() }).where(and(eq(referrals.id, referral.id), eq(referrals.status, 'pending'))); }); } catch (err) { logger.warn({ err }, 'referral both-sides wallet credit failed'); return; } void notifyBonus(referral).catch((err) => logger.warn({ err, referralId: referral.id }, 'referral bonus push failed')); }
async function notifyBonus(referral: typeof referrals.$inferSelect): Promise<void> { const rows = await getDb().select({ id: users.id, name: users.name }).from(users).where(inArray(users.id, [referral.referrerId, referral.refereeId])); const map = new Map(rows.map((row) => [row.id, row.name])); await Promise.all([sendReferralBonusPush({ recipientId: referral.referrerId, refereeName: (map.get(referral.refereeId) ?? 'A friend').split(' ')[0]!, bonusPaise: REFERRAL_BONUS_PAISE }), sendReferralBonusPush({ recipientId: referral.refereeId, refereeName: (map.get(referral.referrerId) ?? 'A friend').split(' ')[0]!, bonusPaise: REFERRAL_BONUS_PAISE })]); }
export async function creditOnHire(_input: { refereeId: string; jobId: string; applicationId: string }): Promise<void> { return; }
export async function listForReferrer(referrerId: string): Promise<PublicReferral[]> { const rows = await getDb().select().from(referrals).where(eq(referrals.referrerId, referrerId)).orderBy(desc(referrals.createdAt)).limit(50); return rows.map(publicRow); }
export interface ReferralSummary { total: number; hired: number; totalBonusPaise: number; }
export async function summarizeForReferrer(referrerId: string): Promise<ReferralSummary> { const rows = await getDb().select({ status: referrals.status, count: sql<number>`count(*)::int`, bonus: sql<number>`coalesce(sum(${referrals.bonusPaise}), 0)::int` }).from(referrals).where(eq(referrals.referrerId, referrerId)).groupBy(referrals.status); let total = 0, hired = 0, totalBonusPaise = 0; for (const row of rows) { total += row.count; if (row.status === 'hired') { hired += row.count; totalBonusPaise += row.bonus; } } return { total, hired, totalBonusPaise }; }
