import { and, desc, eq, gte } from 'drizzle-orm';
import { getDb } from '@/db/client';
import { homeSafeChecks, jobs, users } from '@/db/schema';
import { errors } from '@/lib/errors';
import { logger } from '@/lib/logger';

export type HomeSafeStatus = 'pending' | 'safe';
export interface PublicHomeSafeCheck { id: string; applicationId: string; jobId: string; status: HomeSafeStatus; startedAt: string; confirmedAt: string | null; jobTitle: string | null; }
export async function openOnCheckout(input: { seekerId: string; applicationId: string; jobId: string; employerId: string }): Promise<void> { const sixHoursAgo = new Date(Date.now() - 6 * 60 * 60_000); const [existing] = await getDb().select({ id: homeSafeChecks.id }).from(homeSafeChecks).where(and(eq(homeSafeChecks.applicationId, input.applicationId), eq(homeSafeChecks.status, 'pending'), gte(homeSafeChecks.startedAt, sixHoursAgo))).limit(1); if (!existing) await getDb().insert(homeSafeChecks).values({ ...input, status: 'pending', startedAt: new Date() }); }
export async function listPending(seekerId: string): Promise<PublicHomeSafeCheck[]> { const rows = await getDb().select({ check: homeSafeChecks, title: jobs.title }).from(homeSafeChecks).leftJoin(jobs, eq(homeSafeChecks.jobId, jobs.id)).where(and(eq(homeSafeChecks.seekerId, seekerId), eq(homeSafeChecks.status, 'pending'))).orderBy(desc(homeSafeChecks.startedAt)).limit(10); return rows.map(({ check, title }) => ({ id: check.id, applicationId: check.applicationId, jobId: check.jobId, status: check.status, startedAt: check.startedAt.toISOString(), confirmedAt: check.confirmedAt?.toISOString() ?? null, jobTitle: title ?? null })); }
export async function confirmSafe(seekerId: string, id: string): Promise<PublicHomeSafeCheck> { const [check] = await getDb().select().from(homeSafeChecks).where(and(eq(homeSafeChecks.id, id), eq(homeSafeChecks.seekerId, seekerId))).limit(1); if (!check) throw errors.notFound('Home-safe check not found.'); if (check.status !== 'safe') { await getDb().update(homeSafeChecks).set({ status: 'safe', confirmedAt: new Date() }).where(eq(homeSafeChecks.id, id)); void notifyCircle(seekerId).catch((err) => logger.warn({ err, seekerId }, 'home-safe circle ping failed')); } const [job] = await getDb().select({ title: jobs.title }).from(jobs).where(eq(jobs.id, check.jobId)).limit(1); return { id: check.id, applicationId: check.applicationId, jobId: check.jobId, status: 'safe', startedAt: check.startedAt.toISOString(), confirmedAt: new Date().toISOString(), jobTitle: job?.title ?? null }; }
async function notifyCircle(seekerId: string): Promise<void> { const [seeker] = await getDb().select({ name: users.name, trustCircle: users.trustCircle, share: users.shareShiftsWithCircle }).from(users).where(eq(users.id, seekerId)).limit(1); if (!seeker?.share || !seeker.trustCircle.length) return; const { hashPhone } = await import('@/modules/me/findFriends.service'); const hashes = seeker.trustCircle.map((c) => hashPhone(c.phone)); const matched = await getDb().select({ id: users.id }).from(users).where(and(eq(users.isActive, true), (await import('drizzle-orm')).inArray(users.phoneHash, hashes))); const { sendHomeSafeCirclePush } = await import('@/lib/push'); const firstName = (seeker.name || 'Your contact').split(' ')[0] || 'Your contact'; for (const row of matched) if (row.id !== seekerId) void sendHomeSafeCirclePush({ recipientId: row.id, workerFirstName: firstName }); }
